CREATE TABLE USER (
	USER_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
	PASSWORD BINARY(255) NOT NULL,
	NAME VARCHAR(50) NOT NULL
)

CREATE TABLE PRODUCT (
	PRODUCT_ID BIGINT NOT NULL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(255) NOT NULL,
	PRICE FLOAT NOT NULL
)

CREATE TABLE BOOK (
	PRODUCT_ID BIGINT NOT NULL PRIMARY KEY,
	AUTHOR VARCHAR(255) NOT NULL,
	GENRE VARCHAR(255) NOT NULL,
	PUBLICATIONS VARCHAR(255) NOT NULL,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE APPAREL (
	PRODUCT_ID BIGINT NOT NULL PRIMARY KEY,
	BRAND VARCHAR(255) NOT NULL,
	DESIGN VARCHAR(255) NOT NULL,
	TYPE VARCHAR(255) NOT NULL,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CART (
	CART_ID BIGINT NOT NULL PRIMARY KEY,
	USER_NAME VARCHAR(50) NOT NULL,
	FOREIGN KEY (USER_NAME) REFERENCES USER(USER_NAME),
	
)
CREATE TABLE CART_PRODUCTS (
	ID BIGINT NOT NULL PRIMARY KEY,
	PRODUCT_ID BIGINT NOT NULL, FOREIGN KEY  (PRODUCT_ID ) REFERENCES PRODUCT(PRODUCT_ID),
	QUANTITY INTEGER NOT NULL,
	CART_ID BIGINT NOT NULL, FOREIGN KEY (CART_ID ) REFERENCES CART(CART_ID)
)

DROP TABLE APPAREL
DROP TABLE BOOK
DROP TABLE CART_CART_PRODUCTS
DROP TABLE CART_PRODUCT
DROP TABLE CART
DROP TABLE USER

insert into product values(1,'Steve Jobs', 300)
insert into product values(2,'Java', 100)
insert into product values(3,'Head First', 500)
insert into product values(4,'T-Shirt', 400)
insert into product values(5,'Shirt', 900)

insert into book values('Walter', 'Tech', 'Sage Publishing',1)
insert into book values('Dennis', 'Tech', 'Sage Publishing',2)
insert into book values('Games', 'Tech', 'Sage Publishing',3)
insert into apparel values('Puma','With Print','Half sleeve',4)
insert into apparel values('Luies','Stripes','Full sleeve',5)

insert into user values('TEST@gmail.com', 'TESTER')
insert into cart values(1, 'TEST@gmail.com')